name: omdk
description: "Full modular project"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  bloc: ^8.1.3
  bloc_concurrency: ^0.2.5
  catcher_2: ^1.2.3
  collection: ^1.18.0
  cupertino_icons: ^1.0.2
  dio: ^5.4.1
  equatable: ^2.0.5

  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  intl: any
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  keyboard_actions: ^4.2.0
  meta: ^1.11.0
  modal_bottom_sheet: ^3.0.0

  multi_select_flutter: ^4.1.3
  omdk_api:
    git:
      url: https://github.com/Remorides/omdk-api.git
      ref: main

  omdk_local_data:
    git:
      url: https://github.com/Remorides/omdk-local-data.git
      ref: main

  omdk_mapping:
    git:
      url: https://github.com/Remorides/omdk-mapping.git
      ref: main

  omdk_repo:
    git:
      url: https://github.com/Remorides/omdk-repo.git
      ref: main

  omdk_theme:
    git:
      url: https://github.com/Remorides/omdk-theme.git
      ref: main

  #OPERA
  opera_api_asset:
    git:
      url: https://github.com/Remorides/opera-api-asset.git
      ref: main

  opera_api_auth:
    git:
      url: https://github.com/Remorides/opera-api-auth.git
      ref: main

  opera_api_entity:
    git:
      url: https://github.com/Remorides/opera-api-entity.git
      ref: main

  opera_repo:
    git:
      url: https://github.com/Remorides/opera-repo.git
      ref: main

  omdk_opera_repo:
    git:
      url: https://github.com/Remorides/omdk-opera-repo.git
      ref: main

  path_provider: ^2.1.3
  provider: ^6.1.2
  stream_transform: ^2.1.0
  virtual_keyboard_multi_language: ^1.0.3
  widget_zoom: ^0.0.4

dependency_overrides:
  intl: ^0.18.1

dev_dependencies:
  build_runner: ^2.4.8
  flutter_flavorizr: ^2.2.1
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/.env
    - assets/fonts/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
