name: omdk
description: "Full modular project"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  bloc: ^8.1.3
  bloc_concurrency: ^0.2.5
  catcher_2: ^1.2.3
  cupertino_icons: ^1.0.2
  dio: ^5.4.1
  equatable: ^2.0.5

  #Firebase
  firebase_analytics: ^10.8.8
  firebase_crashlytics: ^3.4.17

  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_dotenv: ^5.1.0
  isar: ^3.1.0+1
  keyboard_actions: ^4.2.0
  meta: ^1.11.0
  modal_bottom_sheet: ^3.0.0

  omdk_api:
    git:
      url: https://github.com/Remorides/omdk-api.git
      ref: main

  omdk_local_data:
    git:
      url: https://github.com/Remorides/omdk-local-data.git
      ref: main

  omdk_repo:
    git:
      url: https://github.com/Remorides/omdk-repo.git
      ref: main

  #Entity: opera asset
  opera_api_asset:
    git:
      url: https://github.com/Remorides/opera-api-asset.git
      ref: main

  opera_api_auth:
    git:
      url: https://github.com/Remorides/opera-api-auth.git
      ref: main

  opera_api_entity:
    git:
      url: https://github.com/Remorides/opera-api-entity.git
      ref: main


  provider: ^6.1.2
  stream_transform: ^2.1.0

dev_dependencies:
  build_runner: ^2.4.8
  flutter_flavorizr: ^2.2.1
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/.env
