name: omdk
description: "Full modular project"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  catcher_2: ^1.2.3
  cupertino_icons: ^1.0.2

  equatable: ^2.0.5
  flutter_bloc: ^8.1.4
  bloc: ^8.1.3
  meta: ^1.11.0

  #Opera API:
  omdk_api:
    git:
      url: https://github.com/Remorides/omdk-api.git
      ref: main

  #Opera Local:
  omdk_local_data:
    git:
      url: https://github.com/Remorides/omdk-local-data.git
      ref: main

  #Opera Repo:
  omdk_repo:
    git:
      url: https://github.com/Remorides/omdk-repo.git
      ref: main

  #Firebase
  firebase_analytics: ^10.8.8
  firebase_crashlytics: ^3.4.17
  dio: ^5.4.1
  provider: ^6.1.2

dev_dependencies:
  flutter_flavorizr: ^2.2.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
